version: 2

models:
  - name: stg_model_1
    description: test
    columns:
      - name: id 
        description: >
          hocus pocus
          pocus hocus
        data_tests:
          - unique
  - name: stg_model_3
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - id
            - color
  - name: stg_model_2
    columns:
      - name: id 
        data_tests:
          - unique
          - not_null