version: 2

models:
  - name: stg_model_4
    columns:
      - name: id
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_model_2')
              field: id

  - name: int_model_4
    columns:
      - name: id
        tests:
          - unique
          - not_null
