name: 'dbt_project_evaluator'
version: '1.0.0'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_project_evaluator:
    marts:
      core:
        int_all_graph_resources:
          +materialized: table   
        int_direct_relationships:
          # required for BigQuery and Redshift for performance/memory reasons
          +materialized: "{{ 'table' if target.type in ['bigquery', 'redshift'] else 'view' }}"
      dag:
        +materialized: table
    staging:
      graph:
        stg_nodes:
          +materialized: table
        stg_node_relationships:
          +materialized: table
      variables:
        stg_naming_convention_folders:
          # required for Redshift because listagg runs only on tables
          +materialized: "{{ 'table' if target.type == 'redshift' else 'view' }}"
        stg_naming_convention_prefixes:
          # required for Redshift because listagg runs only on tables
          +materialized: "{{ 'table' if target.type == 'redshift' else 'view' }}"

vars:
  documentation_coverage_target: 100
  test_coverage_target: 100
  models_fanout_threshold: 3
  max_depth_bigquery: 9
  staging_folder_name: staging
  intermediate_folder_name: intermediate
  marts_folder_name: marts
  staging_prefixes: ['stg_']
  intermediate_prefixes: ['int_']
  marts_prefixes: ['fct_', 'dim_']
  other_prefixes: ['rpt_']