
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_project_evaluator_integration_tests'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'integration_tests'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']

models:
  dbt_project_evaluator_integration_tests:
    # materialize as ephemeral to prevent the fake models from executing, but keep them enabled
    +materialized: ephemeral
  dbt_project_evaluator:
    marts:
      data_tests:
        fct_test_coverage:
          # materialize as a table to ensure SQL query runs successfully
          +materialized: table
      documentation:
        fct_documentation_coverage:
          # materialize as a table to ensure SQL query runs successfully
          +materialized: table

tests:
  dbt_project_evaluator:
    +enabled: false
  dbt_project_evaluator_integration_tests:
    dbt_project_evaluator_schema_tests:
      unique_int_all_dag_relationships_path:
        # Grouping by expressions of type ARRAY is not allowed for BigQuery
        +enabled: "{{ false if target.type in ['bigquery'] else true }}"

seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false

vars:
  # ensure integration tests run successfully when there are 0 of a given model type (extra)
  exclude_packages: ['exclude_package']
  exclude_paths_from_project: ["/to_exclude/","source_3.table_6"]
  model_types: ['base','staging', 'intermediate', 'marts', 'other', 'extra', 'new_model_type']
  # dummy variable used for testing fct_hard_coded_references
  my_table_reference: 'grace_table'
  new_model_type_folder_name: 'my_new_models'
  new_model_type_prefixes: 'nwmdl_'
  insert_batch_size: 100
  too_many_joins_threshold: 3
  chained_views_threshold: 2